# convert.py
import os

# 定义输入和输出文件名
input_filename = "china-list.txt"
output_filename = "china-list.mrs"

def convert_txt_to_mrs():
    """
    读取 china-list.txt 文件，并将其内容转换为 .mrs 规则格式。
    - 域名行转换为 DOMAIN-SUFFIX,域名
    - IP CIDR 行转换为 IP-CIDR,IP/掩码
    """
    if not os.path.exists(input_filename):
        print(f"Error: Input file '{input_filename}' not found.")
        return

    try:
        with open(input_filename, 'r', encoding='utf-8') as f_in, \
             open(output_filename, 'w', encoding='utf-8') as f_out:
            
            f_out.write("# Generated by GitHub Actions\n")
            f_out.write(f"# Source: https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt\n\n")

            for line in f_in:
                line = line.strip()
                if not line or line.startswith('#'):
                    # 跳过空行和注释
                    continue
                
                if '/' in line:
                    # 认为是 IP CIDR
                    f_out.write(f"IP-CIDR,{line}\n")
                else:
                    # 认为是域名
                    f_out.write(f"DOMAIN-SUFFIX,{line}\n")

        print(f"Successfully converted '{input_filename}' to '{output_filename}'")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    convert_txt_to_mrs()
